export const characterClass = {
  archer: {
    className: 'Archer',
    hp: 15,
    str: 15,
    dex: 15,
    min: 15,
    arm: 15,
    res: 15,
    spe: 15,
    luc: 15,
    mov: 5,
    weapons: [
      {
        name: 'Bow',
        category: 'bow',
        damage: 3,
        hit: 5,
        crit: 5,
        range: [2, 3],
        target: ['enemy'],
        skills: [],
      },
    ],
    skills: [],
    modifiers: [],
  },
  cavalier: {
    className: 'Cavalier',
    hp: 15,
    str: 15,
    dex: 15,
    min: 15,
    arm: 15,
    res: 15,
    spe: 15,
    luc: 15,
    mov: 5,
    weapons: [
      {
        name: 'Bow',
        category: 'bow',
        damage: 3,
        hit: 5,
        crit: 5,
        range: [2, 3],
        target: ['enemy'],
        skills: [],
      },
    ],
    skills: [],
    modifiers: [],
  },
  cleric: {
    className: 'Cleric',
    hp: 15,
    str: 15,
    dex: 15,
    min: 15,
    arm: 15,
    res: 15,
    spe: 15,
    luc: 15,
    mov: 5,
    weapons: [
      {
        name: 'Bow',
        category: 'bow',
        damage: 3,
        hit: 5,
        crit: 5,
        range: [2, 3],
        target: ['enemy'],
        skills: [],
      },
    ],
    skills: [],
    modifiers: [],
  },
  fighter: {
    className: 'Fighter',
    hp: 15,
    str: 15,
    dex: 15,
    min: 15,
    arm: 15,
    res: 15,
    spe: 15,
    luc: 15,
    mov: 5,
    weapons: [
      {
        name: 'Bow',
        category: 'bow',
        damage: 3,
        hit: 5,
        crit: 5,
        range: [2, 3],
        target: ['enemy'],
        skills: [],
      },
    ],
    skills: [],
    modifiers: [],
  },
  guardian: {
    className: 'Guardian',
    hp: 15,
    str: 15,
    dex: 15,
    min: 15,
    arm: 15,
    res: 15,
    spe: 15,
    luc: 15,
    mov: 5,
    weapons: [
      {
        name: 'Bow',
        category: 'bow',
        damage: 3,
        hit: 5,
        crit: 5,
        range: [2, 3],
        target: ['enemy'],
        skills: [],
      },
    ],
    skills: [],
    modifiers: [],
  },
  mage: {
    className: 'Mage',
    hp: 15,
    str: 15,
    dex: 15,
    min: 15,
    arm: 15,
    res: 15,
    spe: 15,
    luc: 15,
    mov: 5,
    weapons: [
      {
        name: 'Bow',
        category: 'bow',
        damage: 3,
        hit: 5,
        crit: 5,
        range: [2, 3],
        target: ['enemy'],
        skills: [],
      },
    ],
    skills: [],
    modifiers: [],
  },
  monk: {
    className: 'Monk',
    hp: 15,
    str: 15,
    dex: 15,
    min: 15,
    arm: 15,
    res: 15,
    spe: 15,
    luc: 15,
    mov: 5,
    weapons: [
      {
        name: 'Bow',
        category: 'bow',
        damage: 3,
        hit: 5,
        crit: 5,
        range: [2, 3],
        target: ['enemy'],
        skills: [],
      },
    ],
    skills: [],
    modifiers: [],
  },
  pegasus: {
    className: 'Pegasus',
    hp: 15,
    str: 15,
    dex: 15,
    min: 15,
    arm: 15,
    res: 15,
    spe: 15,
    luc: 15,
    mov: 5,
    weapons: [
      {
        name: 'Bow',
        category: 'bow',
        damage: 3,
        hit: 5,
        crit: 5,
        range: [2, 3],
        target: ['enemy'],
        skills: [],
      },
    ],
    skills: [],
    modifiers: [],
  },
  rogue: {
    className: 'Rogue',
    hp: 15,
    str: 15,
    dex: 18,
    min: 3,
    arm: 6,
    res: 9,
    spe: 18,
    luc: 15,
    mov: 5,
    weapons: [
      {
        name: 'Dagger',
        category: 'dagger',
        damage: 3,
        hit: 5,
        crit: 5,
        range: [1, 2],
        target: ['enemy'],
        skills: [],
      },
    ],
    skills: [],
    modifiers: [],
  },
};
